### ISSUE TITLE
Hardware requirements

### ISSUE THREAD

**Issue by Xyolyp** [lvogt/ioBroker.wireless-mbus#107]
What physical hardware is required to use this adapter? 
I have a water meter which states 868 and OMS on the case but I guess I need some (rather specific?) USB 868 MHz receiver, don't I?
Are there speicific devices which have been tested successfully?

**Comment by lvogt** [comment]
It is basically the very first part of the README:
> This adapter allows to receive wireless M-Bus data from supported receivers. The extent of device implementation varies, but wMBus modes can be configured for all listed devices.
>
> *  Embit WMB modules
> *  Amber Wireless AMB8465 (Beware: Command mode (UART_CMD_Out_Enable) is enabled!)
> *  IMST iM871A
> *  CUL

From the discussion taking place [here (german)](https://forum.iobroker.net/topic/21208/test-adapter-wireless-mbus-v0-8-x/1) it seems to me recently most people either choose CUL or the IMST Stick
