### ISSUE TITLE
No or unknown adapter type selected

### ISSUE THREAD

**Issue by ilkka-aletheia** [lvogt/ioBroker.wireless-mbus#112]
Getting this error message for version 0.8.6. for both iM871A and Amber AMB 8465. Windows 11 laptop and C mode wmbus device. Windows sees both ports OK (virtual com drivers installed for both adapters).

**Comment by lvogt** [comment]
This sounds like the adapter was not correctly installed / is missing some files.
Is there any other hint when you start the adapter with "debug" log level?

**Comment by lvogt** [comment]
Any feedback?

**Comment by lvogt** [comment]
Stale issue. Closed
