### ISSUE TITLE
UI-error in config: Parameter "Gerät nach mehrfachen Fehlern temporär bliockieren" not saved 

### ISSUE THREAD

**Issue by TobiasSt78** [lvogt/ioBroker.wireless-mbus#117]
The mentioned parameter is unmarked and stored. After looking again into the adapter configuration, the parameter is marked again. 
Possible, that it is only a "visual mistake" as the adapter won't start after 10 error messages.

**Comment by lvogt** [comment]
Yep. This is a "display bug". Will be fixed shortly. Thanks for reporting it.

**Comment by lvogt** [comment]
Fixed in fb177acab295c97075cb99f7e99dcb4f5cc0b198
