### ISSUE TITLE
Ignoring contains_crc for Frame B

### ISSUE THREAD

**Issue by Arthedian** [lvogt/ioBroker.wireless-mbus#130]
I discovered that in the "decodeLinkLayer" function of "wmbus_decoder.js," when parsing Frame B, the variable "contains_crc" is not utilized. As a result, if a message doesn't have a CRC, it throws an error even if the message is fine. If I understand correctly, setting "contains_crc" to False should not matter which Frame it is.

**Comment by lvogt** [comment]
That ia true. 
However, the question is, do you have a setup where you receive frame type B with already stripped CRC data?
If yes, please supply a debug log, or at the very least, which receiver do you use?


Am 29. Mai 2023 16:17:04 MESZ schrieb Arthedian ***@***.***>:

**Comment by Arthedian** [comment]
Sorry, I didn't see the notification. I am not using any USB receiver. I receive WMB batch files over FTP, which don't have CRC. Currently, I always set Frame A, so it isn't much of a problem. However, when experimenting with your library, I noticed this and thought I should report it.

**Comment by lvogt** [comment]
Fixed by fda35c6578d5e74690b1eebf9da005b6f230a80a
