### ISSUE TITLE
Config var not set if ELL is ciphered

### ISSUE THREAD

**Issue by Arthedian** [lvogt/ioBroker.wireless-mbus#134]
I am directly using WMBusDecoder because I have my own code for receiving messages. I noticed that if the ELL is ciphered (any Kamstrup meter), the config is not set. If I understood the OMS correctly, variables like cipher mode shouldn't be encrypted, right?

**Comment by lvogt** [comment]
I am not sure what you mean by "config is not set"? The "configword" that is part of the application layer?

If ELL encryption is used, everything afterwards is encrypted, which includes the application layer and therefore also the configword.

**Comment by lvogt** [comment]
Closed due to inactivity
