### ISSUE TITLE
Kamstrup Multical 21__ Unknown compact frame format

### ISSUE THREAD

**Issue by Chris87-ux** [lvogt/ioBroker.wireless-mbus#234]
After setup the Adapter, I got the message: encrypted message and no aeskey provided , which seems to be right.
Than I got the "Geräte Addresse" ( which exactly match with the Serial No. of my Watermeter), so i added the AES Key, which i converted from https://www.python.org/downloads/release/python-31011/.

Now the Error:  Unknown compact frame format popps up every few secounds on my log.

What do i do wrong?

Adapter ist the 0.9.4
JS: 5.0.19 
Node.js: v18.17.1
NPM: 9.6.7
(do I need to update?)

![image](https://github.com/user-attachments/assets/22aaa177-8a26-4a3f-b3de-7a795b7a5b76)

Also posted the log here:
https://forum.iobroker.net/topic/21208/test-adapter-wireless-mbus-v0-9-x/530

Thanks in advance 
/Chris

**Comment by tetzlav** [comment]
I've exactly the same error with my Multical 21. (Adapter v0.9.4 + Node.js: v20.18.1)
I also enabled "Cache für Kompakt-Telegramme", same error.

**Comment by Chris87-ux** [comment]
Additional, i just notice, that even the folders havn't been set. 
![image](https://github.com/user-attachments/assets/13da0679-5d9f-4a8c-b7db-b22b9a35bb76)

**Comment by tetzlav** [comment]
Ich musste feststellen, dass der Adapter bestens funktioniert.  Es werden Werte gelesen und die Datenpunkte korrekt geschrieben. Es kommt nur trotzdem diese Fehlermeldung die mich irritierte...

**Comment by tetzlav** [comment]
I realised that the adapter works perfectly.  Values are read and the data points are written correctly. But I still get this error message that irritates me...

**Comment by Chris87-ux** [comment]
@tetzlav , this would mean, you get all te values from the multical 21 watermeter with your CUL? Just still have the errors on the log? I could live with the errors, as long as i get the values. If you confirm, i just buy the CUL ;-)

**Comment by lvogt** [comment]
The receiver has nothing to do with this.

This meter sends "compact" frames to reduce the telegram length (and save power) and only sends the full telegram from time to time. The adapter can only decode the compact telegram after it has received a full telegram and you **must enable the "Cache für Kompakt Telegramme" setting**.

However, the cache is not persistent, every time the adapter restarts it needs to wait for a full telegram.

**Comment by tetzlav** [comment]
> @tetzlav , this would mean, you get all te values from the multical 21 watermeter with your CUL? Just still have the errors on the log? I could live with the errors, as long as i get the values. If you confirm, i just buy the CUL ;-)

Hmm, my nanoCUL seems not to be stable. It freezes after few hours and needs to be replugged again.
I testet the original (unknown) wmbus firmware from seller (ShcauHaus), the [nanoCUL_r568_mbus_c1t1_bufsize300](nanoCUL_r568_mbus_c1t1_bufsize300) and self compiled mbus firmware from [Rudolf König](https://sourceforge.net/p/culfw/code/HEAD/tree/trunk/culfw/Devices/nanoCUL/).

**Comment by tetzlav** [comment]
> Hmm, my nanoCUL seems not to be stable. It freezes after few hours and needs to be replugged again. I testet the original (unknown) wmbus firmware from seller (SchlauHaus), the [nanoCUL_r568_mbus_c1t1_bufsize300](nanoCUL_r568_mbus_c1t1_bufsize300) and self compiled mbus firmware from [Rudolf König](https://sourceforge.net/p/culfw/code/HEAD/tree/trunk/culfw/Devices/nanoCUL/).

Just for info, if somebody try to use the nanoCUL with iobroker.wireless-mbus: I read an [issue at wmbusmeters](https://github.com/wmbusmeters/wmbusmeters/issues/694) git. You had to [update the bootloader of my nanoCUL](https://docs.arduino.cc/built-in-examples/arduino-isp/ArduinoISP/) to optiboot. Now it seems to be stable without freezes after hours... \O/
