### ISSUE TITLE
Some telegrams fail to parse

### ISSUE THREAD

**Issue by copystring** [lvogt/ioBroker.wireless-mbus#69]
Thanks for implementing C MODE. I was waiting for this.
So I went to try this. It works with my cold water meter but some messages fail to get parsed.
Could you have a look at this?

https://pastebin.com/2tqqd7K6

Thanks

**Comment by copystring** [comment]
I have to add the telegrams are not encrypted.

**Comment by lvogt** [comment]
I have only checked it very briefly, but I guess the only thing you have to do is, to activate the "compact frame cache" in the adapter options. After the first "long" telegram has been received the other ones can be parsed too.

**Comment by copystring** [comment]
Sorry for the late responce. My nanoCUL broke.
Now I have a replacement I activated "compact frame cache".
But the error remains.

Here's a new log with compact frame cache enabled:
https://pastebin.com/vA5GG8rR

**Comment by copystring** [comment]
Actually. After a while the error disappears.
Can it be the right message for compact frame cache appears not right after the start of the adapter?
I guess it makes sense because the water meter sends the messages every X seconds.
We can close this yeah?

**Comment by lvogt** [comment]
Yes, as I wrote, the adapter needs to receive a "long" telegram before the compact ones can be decoded (true for every adapter restart btw.)

**Comment by copystring** [comment]
Makes sense. I forgot about what you wrote :) Thank you!
